# This dockerfile is designed to be run inside the new ECS infrastructure
FROM 317367993082.dkr.ecr.ap-southeast-2.amazonaws.com/node-base-lite-aws:8
MAINTAINER Richard Lennox <rlennox@bauerxcelmedia.com.au>

ENV APP_KEY=now-site

COPY ./src /app
WORKDIR /app
EXPOSE 3001

CMD ["npm", "start"]
