# This dockerfile is designed to be run inside the new ECS infrastructure
FROM 317367993082.dkr.ecr.ap-southeast-2.amazonaws.com/node-base-lite-aws:latest
MAINTAINER Richard Lennox <rlennox@bauerxcelmedia.com.au>

ENV APP_KEY=now-site

# Should set the environment variable when running the container, the default is to run in stubbed mode.
# ENV NODE_ENV=stubbed

COPY ./src /app
WORKDIR /app
EXPOSE 3001

CMD ["npm", "start"]
