jobs:

  - name: now-site_runCI # sync pipeline to CI
    type: runCI
    steps:
      - OUT: now-site-img-master
      - OUT: now-site-img-branch


  - name: now-site-man-branch # manifest for a branch image
    type: manifest
    steps:
      - IN: now-site-img-branch
      - IN: now-site-opts-dev
      - TASK: managed
    flags:
      - now-site


  - name: now-site-man-master # manifest for master image
    type: manifest
    steps:
      - IN: now-site-img-master
      - IN: now-site-opts-dev
      - TASK: managed


  - name: now-site-dev-deploy-branch # DEV deployment for FEATURE BRANCH
    type: deploy
    always:
      - NOTIFY: slack-notifications
    steps:
      - IN: now-site-man-branch # for non-master, don't auto deploy.
        switch: off
      - IN: env-dev-ecs
      - IN: now-site-params-dev
      - IN: now-site-alb-dev-branch
        applyTo:
          - manifest: now-site-man-branch
            image: now-site-img-branch
            port: 3001
      - TASK: managed
        deployMethod: upgrade
  - name: now-site-dev-deploy-master # DEV deployment for MASTER
    type: deploy
    always:
      - NOTIFY: slack-notifications
    steps:
      - IN: now-site-man-master # for master - auto deploy to dev
        switch: on
      - IN: env-dev-ecs
      - IN: now-site-params-dev
      - IN: now-site-alb-dev
        applyTo:
          - manifest: now-site-man-master
            image: now-site-img-master
            port: 3001
      - TASK: managed
        deployMethod: upgrade


  - name: nz-now-site-dev-deploy-master # DEV deployment for MASTER with Region NZ
    type: deploy
    always:
      - NOTIFY: slack-notifications
    steps:
      - IN: now-site-man-master # for master - auto deploy to dev
        switch: on
      - IN: env-dev-ecs
      - IN: now-site-params-dev
      - IN: now-site-params-nz-region
      - IN: nz-now-site-alb-dev
        applyTo:
          - manifest: now-site-man-master
            image: now-site-img-master
            port: 3001
      - TASK: managed
        deployMethod: upgrade


  - name: now-site-stubbed-deploy-master # Stubbed deployment for automation tests
    type: deploy
    steps:
      - IN: now-site-man-master # for master - auto deploy to dev
        switch: on
      - IN: env-dev-ecs
      - IN: now-site-params-stubbed
      - IN: now-site-alb-stubbed
        applyTo:
          - manifest: now-site-man-master
            image: now-site-img-master
            port: 3001
      - TASK: managed
        deployMethod: upgrade


  - name: now-site-automation-test # Test Stub site
    type: runSh
    always:
      - NOTIFY: slack-notifications
    steps:
     - IN: now-site-stubbed-deploy-master
     - IN: now-site-repo
     - TASK:
        - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
        - script: source ~/.nvm/nvm.sh
        - script: nvm install "6.1.0"
        - script: nvm use "6.1.0"
        - script: cd ./IN/now-site-repo/gitRepo/automation
        - script: npm set registry http://npm.digital.bauer-media.net.au
        - script: npm install
        - script: export URL=http://stubbed-site-now-au-37144507.ap-southeast-2.elb.amazonaws.com/
        - script: npm run test:phantom


  - name: now-site-mobile-automation-test # Test Stub site on Browser Stack
    type: runSh
    always:
      - NOTIFY: slack-notifications
    steps:
     - IN: now-site-stubbed-deploy-master
     - IN: now-site-repo
     - TASK:
        - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
        - script: source ~/.nvm/nvm.sh
        - script: nvm install "6.1.0"
        - script: nvm use "6.1.0"
        - script: cd ./IN/now-site-repo/gitRepo/automation
        - script: npm set registry http://npm.digital.bauer-media.net.au
        - script: npm install
        - script: export URL=http://stubbed-site-now-au-37144507.ap-southeast-2.elb.amazonaws.com/
        - script: npm run test:mobile

  - name: nz-now-site-smoke-test # Test Dev Site with NZ config
    type: runSh
    always:
      - NOTIFY: slack-notifications
    steps:
     - IN: nz-now-site-dev-deploy-master
     - IN: now-site-repo
     - TASK:
        - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
        - script: source ~/.nvm/nvm.sh
        - script: nvm install "6.1.0"
        - script: nvm use "6.1.0"
        - script: cd ./IN/now-site-repo/gitRepo/automation
        - script: npm set registry http://npm.digital.bauer-media.net.au
        - script: npm install
        - script: export URL=http://dev-site-now-nz-1643171746.ap-southeast-2.elb.amazonaws.com/
        - script: npm run test:nzlow


  - name: now-site-release-master # Package release for production release
    type: release
    steps:
      - IN: now-site-automation-test
        switch: on
      - IN: now-site-mobile-automation-test
        switch: on
      - IN: nz-now-site-smoke-test
        switch: on
      - IN: now-site-version
      - TASK: managed
