jobs:

  - name: now-site_runCI # sync pipeline to CI
    type: runCI
    steps:
      - OUT: now-site-img-master
      - OUT: now-site-img-branch


  - name: now-site-man-branch # manifest for a branch image
    type: manifest
    steps:
      - IN: now-site-img-branch
      - IN: now-site-opts-sit
      - TASK: managed
    flags:
      - now-site


  - name: now-site-man-master # manifest for master image
    type: manifest
    steps:
      - IN: now-site-img-master
      - IN: now-site-opts-sit
      - TASK: managed


  - name: now-site-sit-deploy-branch # DEV deployment for FEATURE BRANCH
    type: deploy
    always:
      - NOTIFY: slack-notifications
    steps:
      - IN: now-site-man-branch # for non-master, don't auto deploy.
        switch: off
      - IN: env-sit-ecs
      - IN: now-site-params-sit
      - IN: now-site-alb-sit-branch
        applyTo:
          - manifest: now-site-man-branch
            image: now-site-img-branch
            port: 3001
      - TASK: managed
        deployMethod: upgrade
  - name: now-site-sit-deploy-master # DEV deployment for MASTER
    type: deploy
    always:
      - NOTIFY: slack-notifications
    steps:
      - IN: now-site-man-master # for master - auto deploy to SIT
        switch: on
      - IN: env-sit-ecs
      - IN: now-site-params-sit
      - IN: now-site-alb-sit
        applyTo:
          - manifest: now-site-man-master
            image: now-site-img-master
            port: 3001
      - TASK: managed
        deployMethod: upgrade


  - name: nz-now-site-sit-deploy-master # DEV deployment for MASTER with Region NZ
    type: deploy
    always:
      - NOTIFY: slack-notifications
    steps:
      - IN: now-site-man-master # for master - auto deploy to SIT
        switch: on
      - IN: env-sit-ecs
      - IN: now-site-params-sit
      - IN: now-site-params-nz-region
      - IN: nz-now-site-alb-sit
        applyTo:
          - manifest: now-site-man-master
            image: now-site-img-master
            port: 3001
      - TASK: managed
        deployMethod: upgrade


  - name: now-site-test-deploy-master # Stubbed deployment for automation tests
    type: deploy
    steps:
      - IN: now-site-man-master # for master - auto deploy to SIT
        switch: on
      - IN: env-sit-ecs
      - IN: now-site-params-test
      - IN: now-site-alb-test
        applyTo:
          - manifest: now-site-man-master
            image: now-site-img-master
            port: 3001
      - TASK: managed
        deployMethod: upgrade


  - name: now-site-automation-test # Test Stub site
    type: runSh
    always:
      - NOTIFY: slack-notifications
    steps:
     - IN: now-site-test-deploy-master
     - IN: now-site-repo
     - TASK:
        - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
        - script: source ~/.nvm/nvm.sh
        - script: nvm install "6.1.0"
        - script: nvm use "6.1.0"
        - script: cd ./IN/now-site-repo/gitRepo/automation
        - script: npm set registry http://npm.digital.bauer-media.net.au
        - script: npm install
        - script: export URL=http://test-site-now-1875523710.ap-southeast-2.elb.amazonaws.com/
        - script: npm run test:phantom


  - name: now-site-mobile-automation-test # Test Stub site on Browser Stack
    type: runSh
    always:
      - NOTIFY: slack-notifications
    steps:
     - IN: now-site-test-deploy-master
     - IN: now-site-repo
     - TASK:
        - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
        - script: source ~/.nvm/nvm.sh
        - script: nvm install "6.1.0"
        - script: nvm use "6.1.0"
        - script: cd ./IN/now-site-repo/gitRepo/automation
        - script: npm set registry http://npm.digital.bauer-media.net.au
        - script: npm install
        - script: export URL=http://test-site-now-1875523710.ap-southeast-2.elb.amazonaws.com/
        - script: npm run test:mobile

  - name: nz-now-site-smoke-test # Test Dev Site with NZ config
    type: runSh
    always:
      - NOTIFY: slack-notifications
    steps:
     - IN: nz-now-site-sit-deploy-master
     - IN: now-site-repo
     - TASK:
        - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
        - script: source ~/.nvm/nvm.sh
        - script: nvm install "6.1.0"
        - script: nvm use "6.1.0"
        - script: cd ./IN/now-site-repo/gitRepo/automation
        - script: npm set registry http://npm.digital.bauer-media.net.au
        - script: npm install
        - script: export URL=http://sit-site-now-nz-381771907.ap-southeast-2.elb.amazonaws.com/
        - script: npm run test:nzlow

  - name: now-site-smoke-test # Test Dev Site with AU config
    type: runSh
    always:
      - NOTIFY: slack-notifications
    steps:
     - IN: now-site-sit-deploy-master
     - IN: now-site-repo
     - TASK:
        - script: curl dev.publishing-broker.services.bauer-media.internal
        - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
        - script: source ~/.nvm/nvm.sh
        - script: nvm install "6.1.0"
        - script: nvm use "6.1.0"
        - script: cd ./IN/now-site-repo/gitRepo/automation
        - script: npm set registry http://npm.digital.bauer-media.net.au
        - script: npm install
        - script: export URL=http://sit-site-now-au-1673941537.ap-southeast-2.elb.amazonaws.com/
        - script: APP_KEY=now-site npm run sit:au

  - name: FULL-now-site-regression-test # Test Site full regression
    type: runSh
    always:
      - NOTIFY: slack-notifications
    steps:
     - IN: now-site-repo
        switch: off
     - IN: morning-trigger
     - TASK:
        - script: curl dev.publishing-broker.services.bauer-media.internal
        - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
        - script: source ~/.nvm/nvm.sh
        - script: nvm install "6.1.0"
        - script: nvm use "6.1.0"
        - script: cd ./IN/now-site-repo/gitRepo/automation
        - script: npm set registry http://npm.digital.bauer-media.net.au
        - script: npm install
        - script: export URL=http://test-site-now-1875523710.ap-southeast-2.elb.amazonaws.com/
        - script: APP_KEY=now-site npm run all:test


  - name: now-site-release-master # Package release for production release
    type: release
    steps:
      - IN: now-site-automation-test
        switch: off
      - IN: now-site-mobile-automation-test
        switch: off
      - IN: nz-now-site-smoke-test
        switch: off
      - IN: now-site-smoke-test
        switch: off
      - IN: now-site-version
      - TASK: managed
