var homepage_widget = {

    mustreadHeader: '.mustread-teaser-view-grid .home-page__teasers-title',
    mustreadImage: '.mustread-teaser-view-grid .teaser__list-item .teaser__inner img',
    mustreadImageLink: '.mustread-teaser-view-grid .teaser__list-item .teaser__inner > a',
    mustreadTitle: '.mustread-teaser-view-grid .teaser__list-item .teaser__title a',
    promotedHeader: '.promoted-teaser-view-grid .home-page__teasers-title',
    promotedImage: '.promoted-teaser-view-grid .teaser__list-item .teaser__inner img',
    promotedImageLink: '.promoted-teaser-view-grid .teaser__list-item .teaser__inner > a',
    promotedTitle: '.promoted-teaser-view-grid .teaser__list-item .teaser__title a',
    heroImg: '.hero-wrapper',
    heroImgUrl: '.hero-wrapper img',
    heroImgLink: '.hero-wrapper .teaser__image',
    heroCustomLabel: '.hero-wrapper .teaser__badge',
    heroLabelPosition: '.hero-wrapper .teaser__sub-section-container',
    heroTitle: '.hero-wrapper .teaser__title a',
    heroShortTeaser: '.hero-wrapper .teaser__summary',
    heroSource: '.hero-wrapper .hero-teaser__source',
    heroStyle: '.content-wrapper .stripe-bg',
    trendingTitle: '.trending__caption.hide-for-xlarge-up img',
    bottomFeed: '.teaser__list.teaser-view-list',
    topFeedNumber: '.teaser__list.teaser-view-grid article.teaser',
    topFeedTeaserImg: '.teaser__list.teaser-view-grid .teaser__image img',
    topFeedTeaserImgLink: '.teaser__list.teaser-view-grid .teaser__image',
    topFeedTeaserTitle: '.teaser__list.teaser-view-grid .teaser__title a',
    topFeedTeaserSource: '.teaser__list.teaser-view-grid .teaser__source',
    bottomFeedNumber: '.teaser__list.teaser-view-list article.teaser',
    bottomFeedTeaserImg: '.teaser__list.teaser-view-list .teaser__image img',
    bottomFeedTeaserImgLink: '.teaser__list.teaser-view-list .teaser__image',
    bottomFeedTeaserTitle: '.teaser__list.teaser-view-list .teaser__title a',
    bottomFeedTeaserSource: '.teaser__list.teaser-view-list .teaser__source',
    rhsSocialLink: '.page__social-wrapper .social-link a',
    topTeasers: '.teaser-view-grid .teaser__list-item article',
    bottomTeasers: '.teaser-view-list .teaser__list-item article',
    loadMoreFeed: '.repeatable-component div:nth-child(2) article'
};
module.exports = homepage_widget;
