source 'http://rubygems.org'

gem "rake", "10.4.2"
gem "capybara", "2.3.0"
gem "rspec", "2.14.1"
gem "selenium-client", "1.2.18"
gem "selenium-webdriver", "2.42.0"
gem "activesupport", "4.0.2"
gem "phantomjs", "1.9.2.1"
gem "poltergeist", "1.5.0"
gem "cucumber", "1.3.10"
gem "rsolr", "1.0.10"
gem "google-adwords-api", "~> 0.14.0"
gem 'andand'
gem "gherkin", "2.12.2"
gem "parallel"


group :development do
  gem 'pry'
end
